//Blackbox

/*WHat is repl in node.js


REPL (Read-Eval-Print Loop) in Node.js is a simple interactive programming 
environment built into the Node.js runtime. It allows the execution of
 JavaScript code, and the results of such executions are printed to the console.

The name "REPL" is short for "Read-Eval-Print Loop", which describes the way the REPL operates:

READ: The user inputs JavaScript code into the console.
EVAL: The Node.js runtime evaluates the inputted code.
PRINT: The output of the evaluation is printed to the console.
LOOP: Steps 1-3 are repeated as long as the REPL is running. 


REPL in Node.js is particularly useful for quick testing, debugging, and
 experimenting with JavaScript code.
*/